---
# This role installs httpd

- name: Install apache2
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
   - apache2
   - php
   - php-mysql
   - git

- name: apache2 service state
  service:
    name: apache2
    state: started
    enabled: yes
