---
# This role installs httpd

- name: Install apache2
  apt:
    name: ['apache2', 'libapache2-mod-python', 'python-mysqldb', 'php', 'php-mysqls', 'git']
    update_cache: true
    state: present

- name: apache2 service state
  service:
    name: apache2
    state: started
    enabled: yes
