---
- name: Copy deb packages redis-tools
  copy: 
    src: "{{ deb_name_redis_tools }}"
    dest: /tmp/"{{ deb_name_redis_tools }}"
- name: Copy deb packages redis-server
  copy: 
    src: "{{ deb_name_redis_server }}"
    dest: /tmp/"{{ deb_name_redis_server }}"
- name: Install deb packages redis-tools
  apt:  
    deb: /tmp/"{{ deb_name_redis_tools }}"
    dpkg_options: 'force-confold,force-confdef'
- name: Install deb packages redis-server
  apt:  
    deb: /tmp/"{{ deb_name_redis_server }}"
    dpkg_options: 'force-confold'
- name: For Redis change file /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: ''
    insertafter: EOF
    line: 'vm.overcommit_memory = 1'
    create: yes
- name: For Redis change file /etc/rc.local
  lineinfile:
    path: /etc/rc.local
    regexp: ''
    insertafter: EOF
    line: 'echo never > /sys/kernel/mm/transparent_hugepage/enabled'
    create: yes
- name: Configure the redis cnf file with hosts
  template: 
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
  notify: restart haproxy
- name: Autostart Redis
  shell: update-rc.d redis-server defaults