---
# This will install nagios
- name: Install MySQL repository
  apt:
    deb: http://ftp.ru.debian.org/debian/pool/main/n/nagios4/nagios4_4.3.4-3_amd64.deb
    dpkg_options: 'force-confold,force-confdef'

- name: install nagios
  apt: 
    name: ['nagios-nrpe-server', 'nagios-nrpe-plugin', 'nagios-plugins-standard']
    update_cache: true
    state: present
  notify: restart apache2

- name: create nagios config dir
  file: 
    path: /etc/nagios/ansible-managed 
    state: directory

- name: configure nagios
  copy: 
    src: nagios.cfg 
    dest: /etc/nagios/nagios.cfg
  notify: restart nagios

- name: configure localhost monitoring
  copy: 
    src: localhost.cfg 
    dest: /etc/nagios/objects/localhost.cfg
  notify: restart nagios

- name: configure nagios services
  copy: 
    src: ansible-managed-services.cfg 
    dest: /etc/nagios/

- name: create the nagios object files
  template: 
    src: "{{ item + '.j2' }}"
    dest: /etc/nagios/ansible-managed/{{ item }}
  with_items:
    - webservers.cfg
    - dbservers.cfg
    - lbservers.cfg
  notify: restart nagios

- name: start nagios
  service: 
    name: nagios 
    state: started 
    enabled: yes
