---
- name: Copy the code from repository
  git: 
    repo: "{{ repository }}" 
    version: "{{ webapp_version }}" 
    dest: "/var/www/html/"

- name: Install apache2
  apt:
    name: ['python-pip', 'libapache2-mod-python', 'python-mysqldb']
    update_cache: true
    state: present

- name: Install Flask
  pip:
    name: flask
- name: Install Redis
  pip:
    name: redis

- name: Replace python file
  replace:
    dest: /var/www/html/app.py
    regexp: 'host="redis"'
    replace: "{{ redis_host }}"