---
# This role contains common plays that will run on all nodes.

- name: Install new packages
  apt: 
    name: ['ntp', 'mc', 'htop', 'nagios-nrpe-server', 'nagios-plugins']
    update_cache: true
    state: present

- name: Configure ntp file
  template: 
    src: ntp.conf.j2 
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: 
    name: ntpd
    state: started 
    enabled: yes
  tags: ntp
